version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: nest_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Micr@1232
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init-databases.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - microservices-network

  user-service:
    build:
      context: ./backend/user-service
      dockerfile: Dockerfile
    container_name: user-service
    restart: always
    environment:
      NODE_ENV: development
      PORT: 3001
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: Micr@1232
      DB_NAME: user_db
    ports:
      - "3001:3001"
    depends_on:
      - mysql
    networks:
      - microservices-network

  product-service:
    build:
      context: ./backend/product-service
      dockerfile: Dockerfile
    container_name: product-service
    restart: always
    environment:
      NODE_ENV: development
      PORT: 3002
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: Micr@1232
      DB_NAME: product_db
    ports:
      - "3002:3002"
    depends_on:
      - mysql
    networks:
      - microservices-network

  order-service:
    build:
      context: ./backend/order-service
      dockerfile: Dockerfile
    container_name: order-service
    restart: always
    environment:
      NODE_ENV: development
      PORT: 3003
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: Micr@1232
      DB_NAME: order_db
    ports:
      - "3003:3003"
    depends_on:
      - mysql
    networks:
      - microservices-network

  api-gateway:
    build:
      context: ./backend/api-gateway
      dockerfile: Dockerfile
    container_name: api-gateway
    restart: always
    environment:
      NODE_ENV: development
      PORT: 3000
    ports:
      - "3000:3000"
    depends_on:
      - user-service
      - product-service
      - order-service
    networks:
      - microservices-network

volumes:
  mysql_data:

networks:
  microservices-network:
    driver: bridge
